### PR TITLE
Compatibility with rspec-mocks 2.11.3

### PR DESCRIPTION
**Pull request by alxberardi**
Compatibility with changes in https://github.com/rspec/rspec-mocks/blob/a727464658e4c3f08dcff9c62814ade3c5852d73/lib/rspec/mocks/method_double.rb

### CODE REVIEW

**Comment by technicalpickles** [comment]
@jamesarosen another one for review :)

**Comment by jamesarosen** [comment]
@AlessandroBerardi have you run the tests? I can't get them to pass on this branch. I had to first merge master to it to get the gems working. Then, all the tests fail with messages that look like

```
1) [object.should] have_received(method, *args) matches if method is called with correct args
   Failure/Error: @object.stub!(:slice)
   NameError:
     undefined local variable or method `visibility_for_method' for {:expectations=>[], :stubs=>[]}:RSpec::Mocks::MethodDouble
   # ./lib/rspec-spies.rb:13:in `define_proxy_method'
   # ./spec/rspec-spies_spec.rb:11:in `block (2 levels) in <module:Matchers>'
```

**Comment by alxberardi** [comment]
@jamesarosen I apologise for the inconvenience. I have now pushed the required changes. The purpose of this patch is to highlight a change in the more recent versions of rspec which makes the gem incompatible with them. It is therefore important to notice that this patch, in its current state, is not compatible with versions of rspec-mocks prior to 2.11.3.

**Comment by jamesarosen** [comment]
Please don't modify the `gemspec` directly as that file is [generated by Jeweler](https://github.com/technicalpickles/rspec-spies/blob/master/Rakefile#L8-18).

The dependency change leaves us with two options:
1. merge this as-is and release a new major version of rspec-spies that requires `rspec-mocks ~>2.11.3`
2. modify this to work with both the old and new versions of rspec-mocks

I'm fairly sure we want to do the latter. I would recommend checking `respond_to?(:visibility_for_method)` to determine whether we need to define that as a local variable. Perhaps something like

``` ruby
def define_proxy_method
  return if @method_is_proxied
  visibility_declaration = respond_to?(:visibility_for_method} ? visibility_for_method : "#{visibility} :#{method_name}"
  object_singleton_class.class_eval <<-EOF, __FILE__, __LINE__ + 1
    def #{method_name}(*args, &block)       
      __mock_proxy.record_message_received :#{method_name}, *args, &block   
      __mock_proxy.message_received :#{method_name}, *args, &block
    end
    #{visibility_declaration}
  EOF
  @method_is_proxied = true
end
```

I'd like to figure out what exactly the fix for 2.11.3 is. As far as I can tell, the only changes you made were
1. turn it into a no-op if it's already been done. This seems to me like a bug fix and has no impact on version compatibility.
2. add `1` to the line number. This is a bug fix and has no impact on version compatibility.
3. don't save `@method_name` to the local variable `method_name`. This is an internal implementation detail and has no impact on version compatibility.
4. use the `visibility_for_method` method

I'm confused about this last one. rspec-mocks's definition in 2.11.3 is exactly the same as what this used before. Is the problem that something else is redefining it and you want rspec-spies to obey the override? If that's really the only problem, then we can define that method ourselves and have everyone use the 2.11.3-compatible version:

``` ruby
def define_proxy_method
  return if @method_is_proxied
  object_singleton_class.class_eval <<-EOF, __FILE__, __LINE__ + 1
    def #{method_name}(*args, &block)       
      __mock_proxy.record_message_received :#{method_name}, *args, &block   
      __mock_proxy.message_received :#{method_name}, *args, &block
    end
    #{visibility_for_method}
  EOF
  @method_is_proxied = true
end

def visibility_for_method
  "#{visibility} :#{method_name}"
end
```

**Comment by alxberardi** [comment]
@jamesarosen the only important change is the bug fix introduced by the check and assignment on @method_is_proxied (point 1). I lazily grabbed the code from rspec-mocks 2.11.3 and added the call to record_message_received. I apologise for the quick fix, I should have reviewed the code better before submitting the pull request.
Anyway, I believe that the compatibility issue with visibility_for_method can be easily overcome by reverting the code to the previous state and adding the bug fixes (points 1 and 2).

**Comment by jamesarosen** [comment]
@AlessandroBerardi do you want to do that or shall I? Since we're in here, we might as well back-port `visibility_for_method` so we don't accidentally run into this problem again.

**Comment by alxberardi** [comment]
I reverted the gem related commits and back ported `visibility_for_method` as suggested. Specs are passing.

**Comment by jamesarosen** [comment]
Thanks for all this :)

**Comment by alxberardi** [comment]
@jamesarosen Thank you!

**Pull request merged**
