### PR TITLE
Fix for "uninitialized constant RSpec::Mocks::ArgumentListMatcher"

### PR DESCRIPTION
**Pull request by tucker250**
This fixes issue 12: https://github.com/technicalpickles/rspec-spies/issues/12

### CODE REVIEW

**Comment by linko** [comment]
@tucker250 Thanks! It works for me.

**Comment by smdern** [comment]
Yes. Please merge!

**Comment by technicalpickles** [comment]
@jamesarosen mind taking a look at this?

**Comment by jamesarosen** [comment]
Not at all. Expect an update Tuesday afternoon, PST.

**Comment by jamesarosen** [comment]
RSpec v2.8.0 (which this claims to be compatible with) doesn't have that file. Instead, it has `rspec/mocks/argument_expectation`. My suggestion would be

``` ruby
argument_expectation_class = begin
                               require 'rspec/mocks/argument_list_matcher'
                               RSpec::Mocks::ArgumentListMatcher
                             rescue LoadError
                               require 'rspec/mocks/argument_expectation'
                               RSpec::Mocks::ArgumentExpectation
                             end
```

@tucker250 have you run the appraisal tests? Those ensure that this gem is compatible with RSpec v2.8 and v2.11.

**Pull request closed without merging**
