### PR TITLE
Updated for rspec 2.5

### PR DESCRIPTION
**Pull request by peteglondon**
Got all existing specs working with rspec 2.5.

### CODE REVIEW

**Comment by technicalpickles** [comment]
Very cool! Been meaning to revisit spies, so this pull request is a good motivator :)

**Comment by darkofabijan** [comment]
Any idea when this will be merged?

**Comment by technicalpickles** [comment]
I'm not actively using this actively anymore, so it's pretty low on my open source totem pole. If anyone wants to step up to help maintain and move it along, please let me know :)

**Comment by technicalpickles** [comment]
Merged & released as 2.0.0. Enjoy :)

**Comment by darkofabijan** [comment]
Awesome. :) Thanks!

**Pull request merged**
